minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  undici@<5.29.0: '>=5.29.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
